staticSites:
  - name: chictryon-frontend
    buildCommand: npm run build
    publishPath: ./dist   # or build if CRA
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
